# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jigsaw.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=jigsaw.models._createId, max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=150)),
                ('public', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0, editable=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='jigsaw.Game')),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(editable=False)),
                ('points', models.IntegerField(default=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='jigsaw.Game')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150)),
                ('meaning', models.CharField(max_length=250)),
                ('points', models.IntegerField(default=50)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='jigsaw.Round')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='round',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='jigsaw.Round'),
        ),
    ]
