# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='last',
            field=models.IntegerField(default=2),
        ),
    ]
