# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0002_round_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='last',
        ),
        migrations.AddField(
            model_name='game',
            name='last',
            field=models.IntegerField(default=2),
        ),
    ]
