# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jigsaw.models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0003_auto_20160315_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('totaltime', models.IntegerField(default=1800)),
                ('passedtime', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrintDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=jigsaw.models._createId, max_length=32)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prints', to='jigsaw.Round')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='public',
        ),
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='jigsaw.Game'),
        ),
        migrations.AddField(
            model_name='player',
            name='instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='jigsaw.GameInstance'),
            preserve_default=False,
        ),
    ]
