# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0005_auto_20160315_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['word']},
        ),
    ]
