# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0006_auto_20160315_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='host',
            new_name='creator',
        ),
    ]
