# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0007_auto_20160316_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='alias',
            field=models.CharField(default='', max_length=90),
            preserve_default=False,
        ),
    ]
