# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0008_gameinstance_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='system',
            field=models.BooleanField(default=False),
        ),
    ]
