# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0010_gameinstance_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 17, 8, 21, 41, 218000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
