# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0011_gameinstance_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameinstance',
            options={'ordering': ['-time']},
        ),
    ]
