# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0012_auto_20160317_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
