# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0014_roundreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundreport',
            name='boardinfo',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
