# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0015_roundreport_boardinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
