# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0016_gameinstance_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='type',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
