# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigsaw', '0017_round_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='type',
            field=models.CharField(blank=True, choices=[('J', 'Jigsaw'), ('M', 'Matching')], max_length=1),
        ),
    ]
